/**
 * Generates supabase/seed.sql from the catalog data in src/data.
 *   node scripts/generate-seed.mjs
 * Safe to re-run: uses ON CONFLICT DO NOTHING, so it never overwrites
 * products or gallery items you've edited in the admin.
 */
import { writeFileSync } from 'node:fs';
import { categories } from '../src/data/categories.js';
import { seedProducts } from '../src/data/seedProducts.js';
import { seedGallery } from '../src/data/seedGallery.js';

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const num = (v) => (v === null || v === undefined || v === '' ? 'null' : Number(v));
const bool = (v) => (v ? 'true' : 'false');
const arr = (a = []) => (a.length ? `array[${a.map(q).join(', ')}]::text[]` : `'{}'::text[]`);
const json = (v) => `${q(JSON.stringify(v ?? null))}::jsonb`;

const out = [];
out.push('-- Generated by scripts/generate-seed.mjs — do not edit by hand.');
out.push('begin;');

out.push('\n-- Categories');
categories.forEach((c, i) => {
  const image = c.image ? { url: c.image.url, srcSet: c.image.srcSet, alt: c.image.alt, width: c.image.width, height: c.image.height } : null;
  out.push(`insert into public.product_categories (id, name, slug, description, image, sort) values (${q(c.id)}, ${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${json(image)}, ${i}) on conflict (id) do nothing;`);
});

out.push('\n-- Products (prices are placeholders — edit in Admin → Products)');
for (const p of seedProducts) {
  out.push(`insert into public.products (id, slug, name, description, category_id, price, sale_price, video, featured, customizable, active, archived, inventory, low_stock_threshold, estimated_production_time, sizes, colors, occasions, popularity, customization, created_at) values (${[
    q(p.id), q(p.slug), q(p.name), q(p.description), q(p.category), num(p.price), num(p.salePrice), q(p.video),
    bool(p.featured), bool(p.customizable), bool(p.active), bool(p.archived), num(p.inventory), num(p.lowStockThreshold ?? 3),
    q(p.estimatedProductionTime), arr(p.sizes), arr(p.colors), arr(p.occasions), num(p.popularity ?? 0),
    json(p.customization || {}), q(p.createdAt),
  ].join(', ')}) on conflict (id) do nothing;`);
  (p.images || []).forEach((img, i) => {
    out.push(`insert into public.product_images (product_id, url, src_set, alt, width, height, sort) select ${q(p.id)}, ${q(img.url)}, ${q(img.srcSet)}, ${q(img.alt)}, ${num(img.width)}, ${num(img.height)}, ${i} where not exists (select 1 from public.product_images where product_id = ${q(p.id)} and url = ${q(img.url)});`);
  });
}

out.push('\n-- Gallery');
for (const g of seedGallery) {
  out.push(`insert into public.gallery (id, title, category_id, description, images, featured, published, created_at) values (${[
    q(g.id), q(g.title), q(g.category), q(g.description), json(g.images), bool(g.featured), bool(g.published), q(g.createdAt),
  ].join(', ')}) on conflict (id) do nothing;`);
}

out.push('\ncommit;');
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log(`seed.sql: ${categories.length} categories, ${seedProducts.length} products, ${seedGallery.length} gallery items`);
